@startuml

actor Usuario
boundary "Frontend" as Frontend
control NextAuth
collections "Google API" as GoogleAPI
control "Prisma Adapter" as Prisma
database Database

entity "User" as User
entity "Session" as Session
entity "Account" as Account

Usuario -> Frontend: Iniciar sesión
Frontend ->> NextAuth: Solicitar autenticación
NextAuth ->> GoogleAPI: Autenticar con OAuth
GoogleAPI -->> NextAuth: Retornar token de usuario
NextAuth -> Prisma: Buscar usuario por email
Prisma -> Database: Consultar usuario por email
Database --> Prisma: Retorna usuario
Prisma -> User: Convierte a objeto usuario

alt Usuario no existe
    Prisma -> Database: Insertar nuevo usuario
    Database --> Prisma: Retornar nuevo usuario
    Prisma -> User: Mapear nuevo usuario
    Prisma -> Database: Insertar cuenta
    Database --> Prisma: Retornar cuenta
    Prisma -> Account: Mapear cuenta
end

NextAuth -> Prisma: Registrar sesión
Prisma -> Database: Insertar registro
Database --> Prisma: Retornar resultado
Prisma -> Session: Mapear resultado
Session -->> NextAuth: Retornar objeto sesión
NextAuth -->> Frontend: Retornar sesión

alt Autenticado
    Frontend -> Frontend: Renderizar vista de usuario
else No autenticado
    Frontend -> Frontend: Mostrar pantalla de inicio
end

@enduml
