@startuml

actor User
boundary "Frontend" as Frontend
control tRPC
control "Prisma Adapter" as Prisma
database Database
entity "Usuario" as Usuario
boundary "Dashboard Doctor" as DoctorDashboard
boundary "Dashboard Paciente" as PacienteDashboard
boundary "Dashboard Diagnostico" as DiagnosticoDashboard

User -> Frontend: Acceder al sistema
Frontend ->> tRPC: Consultar rol
tRPC -> Prisma: Consultar usuario en BD
Prisma -> Database: Consultar rol de usuario
Database --> Prisma: Retornar consulta de rol
Prisma -> Usuario: Convertir consulta en objeto
Usuario -->> tRPC: Retornar rol del usuario
tRPC -->> Frontend: Retornar rol

alt Rol Doctor
    Frontend -> DoctorDashboard: Renderizar Dashboard Doctor
else Rol Paciente
    Frontend -> PacienteDashboard: Renderizar Dashboard Paciente
else Rol Farmacéutico
    Frontend -> DiagnosticoDashboard: Renderizar Dashboard Farmacéutico
end

@enduml
