@startuml

actor Administrativo
boundary "Frontend" as Frontend
boundary "Gestiona perfil" as ManageView
control tRPC
control "Prisma Adapter" as Prisma
database Database
entity "Historial" as Patient

Administrativo -> Frontend: Acceder al sistema
Frontend -> ManageView: Renderizar vista de administrativo
ManageView -> Frontend: Mostrar vista de administrativo 

Administrativo -> Frontend: Consultar historial de paciente
Frontend ->> tRPC: Consultar existencia de historial
tRPC -> Prisma: Consultar historial de paciente
Prisma -> Database: Consultar historial de paciente 
Database --> Prisma: Retornar historial de paciente
Prisma -> Patient: Mapear historial de paciente
Patient -->> tRPC: Retornar historial de paciente
tRPC -->> Frontend: Mostrar historial de paciente

alt Historial no existe
    Administrativo -> Frontend: Registrar historial de paciente
    Frontend ->> tRPC: Registrar historial de paciente
    tRPC -> Prisma: Crear historial de paciente
    Prisma -> Database: Insertar historial de paciente
    Database --> Prisma: Retornar confirmación
    Prisma -> Patient: Mapear retorno
    Patient -->> tRPC: Retornar confirmación
    tRPC -->> Frontend: Enviar confirmación 
end

@enduml
