@startuml
actor Medico

boundary "Frontend" as Frontend
entity "Orden Evaluación" as OrdenCtrl
control tRPC
control "Prisma Adapter" as Prisma
database Database
control "Sistema de Notificaciones" as Notif

' --- Notificación al Médico ---
Notif ->> Medico: Enviar notificación (Orden atendida)
Medico -> Frontend: Recibir notificación y acceder a detalles de la orden

' --- Consulta de la Orden Actualizada ---
Frontend ->> OrdenCtrl: Solicitar detalles de la orden atendida
OrdenCtrl -> tRPC: Obtener detalles actualizados de la orden
tRPC -> Prisma: Query a la base de datos
Prisma -> Database: Ejecutar consulta
Database --> Prisma: Retorno de datos
Prisma --> tRPC: Mapear resultados
tRPC -->> OrdenCtrl: Retorno de datos actualizados
OrdenCtrl -->> Frontend: Mostrar detalles de la orden
Frontend -> Medico: Visualizar orden con resultados y observaciones

@enduml
