@startuml
actor "Paciente" as Paciente

boundary "Frontend" as Frontend
control "Sistema de Notificaciones" as Notif
entity "Plan de Atención" as PlanCtrl
control "Prisma Adapter" as Prisma
database Database
control tRPC

'--- Generación y Envío de la Notificación ---
tRPC ->> Notif: Notificar nuevo plan de atención
Notif -->> Frontend: Enviar notificación (push)
Frontend -> Paciente: Mostrar notificación en la interfaz

'--- Interacción del Paciente con la Notificación ---
Paciente -> Frontend: Seleccionar notificación
Frontend ->> tRPC: Solicitar detalles del plan de atención
tRPC -> Prisma: Consultar detalles del plan
Prisma -> Database: Consultar plan en BD
Database --> Prisma: Retorno de datos del plan
Prisma --> tRPC: Mapear resultados
tRPC -->> Frontend: Enviar detalles del plan
Frontend -> Paciente: Mostrar detalles del plan de atención

@enduml
