@startuml HistoriaClinicaClassDiagram
class Medico {

}

class Paciente {
    fechaNacimiento: Date
    direccion: String
    telefono: String
}

class HistorialClinico {    
    fecha: Date
    diagnostico: String
    tratamiento: String
    observaciones: String
    prescripcion: String
    proximoControl: Date
}

class IndicacionMedica {
    id: String
    fecha: Date
    horario: String
}


' Relaciones
Paciente "1" -- "1" HistorialClinico : tiene
HistorialClinico "1" -- "1..*" IndicacionMedica : incluye
Medico "1" -- "1..*" IndicacionMedica : genera
@enduml
