@startuml IndicacionMedicaClassDiagram

class HistorialClinico {
}


class IndicacionMedica {
    id: String
    fecha: Date
    horario: String
}

class Dosis {
    medicamento: Medicamento
    cantidad: String
    unidad: String 
    frecuencia: String
    duracion: String
    fechaDeCreacion: Date
    fechaDeActualizacion: Date
    medioDeConsumo: String

}

'Es como producto
class Medicamento {
    nombre: String
    presentacion: String    
    fechaDeCreacion: Date
    fechaDeActualizacion: Date

}

' Relaciones

HistorialClinico "1" -- "1" IndicacionMedica : incluye
IndicacionMedica "1" -- "1..*" Medicamento : contiene
Medicamento "1" - "1..*" Dosis : tiene

@enduml
