@startuml RecetaMedicaClassDiagram

class IndicacionMedica {
    id: String
    fecha: Date
    horario: String
}
class RecetaMedica {
    id: String
    fecha: Date
    horario: String
    indicacion: IndicacionMedica
    medicamento: Medicamento
    fechaDeCreacion: Date
    cantidad: String
    unidad: String 
}
class Medicamento {
    nombre: String
    presentacion: String    
    fechaDeCreacion: Date
    fechaDeActualizacion: Date

}
class Medico {

}

IndicacionMedica "1" -- "1" RecetaMedica : incluye
RecetaMedica "1" -- "1..*" Medicamento : contiene
Medico "1" -- "1..*" RecetaMedica : genera

@enduml