@startuml SesionDeUsuarioClassDiagram
class Usuario {
    nombre: String
    apPaterno: String
    apMaterno: String
    email: String    
    imagen: String    
    fechaDeCreacion: DateTime
    fechaDeActualizacion: DateTime
}

class Sesion {
  sessionToken:String
  usuario: Usuario  
  expiraEn: DateTime
  fechaDeCreacion: DateTime
  fechaDeActualizacion: DateTime
}

class Cuenta {
    usuario: Usuario  
    tipo: String
    proveedor: String
    idCuentaProveedor: String
    refreshToken: String
    accessToken: String
    expiraEn: Int
    tipoDeToken: String
    alcance: String
    idToken: String
    estadoDeSesion: String
    fechaDeCreacion: DateTime
    fechaDeActualizacion: DateTime
}

class Medico {
    nroDeColegiatura: String
    especialidad: String
    universidad: String
    fechaDeInicio: DateTime
    fechaDeFin: DateTime        
}

class Paciente {
    fechaDeInicio: DateTime
    fechaDeFin: DateTime
    listarPacientes(): Paciente[]
    registrarPaciente(): Paciente
    editarPaciente(): Paciente
    eliminarPaciente(): void
}

class Administrador {
    nroDeEmpleado: String
    fechaDeInicio: DateTime
    fechaDeFin: DateTime

}

class Farmaceutico {
    nroDeLicencia: String
    fechaDeInicio: DateTime
    fechaDeFin: DateTime
}


Usuario <|-- Paciente
Usuario <|-- Medico
Usuario <|-- Administrador
Usuario <|-- Farmaceutico
Usuario "1" -- "1..*" Cuenta
Usuario "1" -- "1..*" Sesion

@enduml