@startuml VistaDeUsuarioClassDiagram
class Usuario {
    nombre: String
    apPaterno: String
    apMaterno: String
    email: String    
    imagen: String    
    fechaDeCreacion: DateTime
    fechaDeActualizacion: DateTime
}
class VistaDeUsuario {
    usuario: Usuario[]
    nombreDeVista: String
    fechaDeCreacion: DateTime
    fechaDeActualizacion: DateTime
}
Usuario "1" -- "1..*" VistaDeUsuario
@enduml

