@startuml

actor administrador as "Administrador"

rectangle GestionDeVistasDeUsuario {
    usecase listarUsuarios as "Listar usuarios"  
    usecase crearVistasDeUsuario as "Crear vistas de usuario"  
    usecase modificarVistasDeUsuario as "Modificar vistas de usuario"
    usecase eliminarUsuario as "Eliminar usuario"    
}

administrador --> listarUsuarios
administrador --> crearVistasDeUsuario
administrador --> modificarVistasDeUsuario
administrador --> eliminarUsuario

@enduml