@startuml

!define COMPONENT Component

database "PostgreSQL"
package "src" {
    folder "prisma" {
        COMPONENT "schema.prisma"
    }
    folder "server" {
        COMPONENT "prisma.ts"
    }
}

' Relaciones
"prisma.ts" --> "schema.prisma" : Utiliza esquema para definir modelos
"prisma.ts" --> PostgreSQL : Conexión ORM a PostgreSQL
"prisma.ts" --> "env.js" : Verifica entorno de ejecución de Node

@enduml
