@startuml


!define COMPONENT Component

package "src" {
     folder "pages" {
        folder "api"{           
            folder "trpc"{
                COMPONENT "[trpc].ts"
            }                
        }
      
        
    }
    folder "server" {       
        folder "routers" {
            COMPONENT "_app.ts"
        }                       
                        
    }
    folder "utils" {
        COMPONENT "trpc.ts"
    }
   
}

' Relaciones
"trpc.ts"-->"_app.ts": Importa el tipo de las rutas
"trpc.ts"-->"[trpc].ts": Busca la dirección del cliente para construir su lote
"trpc.ts"-->".env": Verifica entorno de ejecución de Node y obtiene url del servidor http 


@enduml
